//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allocation
    {
        public string StudentNumber { get; set; }
        public string AllId { get; set; }
        public string StaffNumber { get; set; }
        public int Id { get; set; }
    
        public virtual ProjectSupervisor ProjectSupervisor { get; set; }
        public virtual Student Student { get; set; }
    }
}
