//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Completed
    {
        public int id { get; set; }
        public Nullable<double> Progress { get; set; }
        public string StudentNumber { get; set; }
        public string Type { get; set; }
    }
}
