//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public string EventID { get; set; }
        public bool isFullDay { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Description { get; set; }
        public string Subject { get; set; }
        public string StudentNumber { get; set; }
        public string StaffNumber { get; set; }
        public string ThemeColor { get; set; }
    
        public virtual ProjectSupervisor ProjectSupervisor { get; set; }
        public virtual Student Student { get; set; }
    }
}
