//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingRecord
    {
        public System.DateTime Date { get; set; }
        public System.DateTime StartTime { get; set; }
        public string StaffNumber { get; set; }
        public string StudentNumber { get; set; }
        public string Minutes { get; set; }
        public string Agenda { get; set; }
        public string MeetingId { get; set; }
    
        public virtual Meeting Meeting { get; set; }
        public virtual ProjectSupervisor ProjectSupervisor { get; set; }
        public virtual Student Student { get; set; }
    }
}
