//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Milestone
    {
        public string MilestoneID { get; set; }
        public string Text { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<int> Duration { get; set; }
        public string ProjectNumber { get; set; }
        public string Type { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<double> Progress { get; set; }
        public int Id { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
