//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public string ProjectNumber { get; set; }
        public string ProjectName { get; set; }
        public System.DateTime DueDate { get; set; }
        public string StudentNumber { get; set; }
    }
}
